Algoritmo "vetor"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/06/2020
Var
vet : vetor [1..4] de caractere
i: inteiro
Inicio
para i := 1 ate 4 faca
     escreva("digite um nome:")
     leia(vet[i])
fimpara
escreva(vet[1],", ",vet[2],", ",vet[3],", ",vet[4])
Fimalgoritmo